name: Android CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - 'release/*'
    tags:
      - 'v*'

permissions:
  contents: read
  checks: write
  statuses: write

jobs:
  build-and-test:
    name: Build · Unit tests · Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build (assembleDebug)
        run: ./gradlew assembleDebug --no-daemon

      - name: Run unit tests
        run: ./gradlew test --no-daemon

      - name: Run Android lint
        run: ./gradlew lint --no-daemon

      - name: Upload CI artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            app/build/reports
            app/build/outputs
